set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# floating windows
bind C-g display-popup -E "tmux new-session -A -s scratch"

# for neovim
resurrect_dir="$XDG_STATE_HOME/tmux/resurrect"
set -g @resurrect-dir $resurrect_dir
set -g @resurrect-hook-post-save-all 'target=$(readlink -f $resurrect_dir/last); sed "s| --cmd .*-vim-pack-dir||g; s|/etc/profiles/per-user/$USER/bin/||g; s|/home/$USER/.nix-profile/bin/||g" $target | sponge $target'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind %
unbind '"'
bind 'h' split-window -v -c "#{pane_current_path}"
bind 'v' split-window -h -c "#{pane_current_path}"
bind-key 'L' run-shell -b "$XDG_CONFIG_HOME/tmux/plugins/tmux-fzf/scripts/session.sh switch"

run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
